[project]
name = "federated-crosschain-toolkit"
authors = ["Crosschain Federation Team"]
description = "A decentralized toolkit for multi-chain collaboration and governance"
telemetry = false
requirements = []
[contracts.crosschain-federation]
path = "contracts/crosschain-federation.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
